### ISSUE TITLE
Need manually `GitStateChangedAction()` right after including git_watcher if your lib are compiled by globbing sources

### ISSUE THREAD

**Issue by district10** [andrew-hardin/cmake-git-version-tracking#25]
I'm configuring my c++ project just like <https://github.com/andrew-hardin/cmake-git-version-tracking/blob/master/better-example/CMakeLists.txt>, but I need to run `cmake .. && make` twice to get the linking works.

I found that the first time I run `cmake .. && make`, my lib compiled without git.cc.

At the time I wrote this issue, I found my mistake:

```
file(GLOB_RECURSE SOURCES src/**/*.cpp "${PROJECT_BINARY_DIR}/git.cc")
# globbing in cmake will ignore non-existing source, so the first time of `cmake` (before `make` generating git.cc) will not include git.cc
```

```
set(PRE_CONFIGURE_FILE cmake/git.cc.in)
set(POST_CONFIGURE_FILE "${PROJECT_BINARY_DIR}/git.cc")
include(cmake/git_watcher.cmake)
GitStateChangedAction() # I need this extra line
```

It's not a mistake of your cmake script. Just firing an issue hopping it to be helpful for others.

**Comment by andrew-hardin** [comment]
Thank you for opening an issue to help future Googlers.

I'm not sure manually calling `GitStateChangedAction()` is the best choice. Yes, it'll generate `git.cc`, but it'll also run every time the project gets reconfigured (e.g. you modify a CMakeLists and re-run the build). There may be a cleaner way to accomplish what you're trying to do. Could share the full CMakeLists or post the link to a minimum working or broken example?

This is completely unrelated, but it's nice to meet a fellow Dvorak user :keyboard:

**Comment by district10** [comment]
@andrew-hardin Minimum working example: https://github.com/district10/cmake-git-version-tracking

```
cd better-example
mkdir build && cd build
cmake .. && make # fails
cmake .. && make # success
```

(as a Dvorak user for ~8 years :smiley: )

**Comment by andrew-hardin** [comment]
Thanks for the example - it exhibited the behavior you described. I don't have an elegant solution, I think the best workaround is to move the `${POST_CONFIGURE_FILE}`  back to the `add_library`, e.g.:

```
add_library(git STATIC ${SOURCES} ${POST_CONFIGURE_FILE})
# Or, you could  manually append the post-configure file to the ${SOURCES} list.
```

This preserves the behavior of only recompiling/relinking after the git state changes.
