### ISSUE TITLE
Git info not properly set

### ISSUE THREAD

**Issue by district10** [andrew-hardin/cmake-git-version-tracking#26]
Generated `git.cc` has something like:

```
bool GitMetadata::Populated() {
    return ;
}
bool GitMetadata::AnyUncommittedChanges() {
    return ;
}
std::string GitMetadata::CommitBody() {
    return ;
}
```

Seems env variables not properly set. (Not quite sure how did I get there. I'll provide a mimimum process to reproduce it later.)

I would suggest

```
bool GitMetadata::Populated() {
    return "@GIT_RETRIEVED_STATE@" == std::string("false");
}
bool GitMetadata::AnyUncommittedChanges() {
    return "@GIT_IS_DIRTY@" == std::string("false");
}
std::string GitMetadata::CommitBody() {
    return "@GIT_COMMIT_BODY@";
}
```
and not surround these variables with `"` quotation mark in cmake. This would be more robust.

**Comment by andrew-hardin** [comment]
I merged a PR this evening related to checking the exit code from the `git` command. If a git command fails, it should print the command that failed and whatever was written to `stderr`. Would you be willing to pull down `master` and give it a try? At minimum, it should help troubleshoot why some of the fields are empty...

**Comment by district10** [comment]
> I merged a PR this evening related to checking the exit code from the `git` command. If a git command fails, it should print the command that failed and whatever was written to `stderr`. Would you be willing to pull down `master` and give it a try? At minimum, it should help troubleshoot why some of the fields are empty...

I reproduced the `return ;` thing. Apply this patch:

```diff
diff --git a/better-example/CMakeLists.txt b/better-example/CMakeLists.txt
index 0cb6d91..f0e8ae0 100644
--- a/better-example/CMakeLists.txt
+++ b/better-example/CMakeLists.txt
@@ -6,6 +6,7 @@ project(BetterExample)
 set(PRE_CONFIGURE_FILE "git.cc.in")
 set(POST_CONFIGURE_FILE "${CMAKE_CURRENT_BINARY_DIR}/git.cc")
 include(../git_watcher.cmake)
+GitStateChangedAction()
 
 # Create a library out of the compiled post-configure file.
 add_library(git STATIC ${POST_CONFIGURE_FILE})
```

```
cd better-example
mkdir build && cd build
cmake .. && make # success
cmake .. && make # fails, see git.cc now
```

Seems I shouldn't call `GitStateChangedAction()` manually. I'll use `add_library(git STATIC ${SOURCES} ${POST_CONFIGURE_FILE})` as you suggested in https://github.com/andrew-hardin/cmake-git-version-tracking/issues/25.

You can have a closer look here. Thanks.

**Comment by andrew-hardin** [comment]
Thank you, I can see what led to the empty variables. I'm not sure how to mitigate this mistake for future users. I may go through and modify function names to reflect that they're "private" functions (e.g. add a `__` prefix).
