### ISSUE TITLE
GIT_COMMIT_BODY is the only value with built-in quotes

### ISSUE THREAD

**Issue by brunexgeek** [andrew-hardin/cmake-git-version-tracking#34]
Is there a reason **GIT_COMMIT_BODY** has quotes included in the value while all other strings don't?

**Comment by andrew-hardin** [comment]
This commit stands out: https://github.com/andrew-hardin/cmake-git-version-tracking/commit/b9e28e98f5276b162bedb1792ec337ee875ab4c5. My naive reading of the change is that quotes were removed from both the C and C++ examples to allow for multi-line commit messages.

**Comment by brunexgeek** [comment]
I see. However, I believe that all content would always be one-line, as new lines are escaped.
